package constants

enum class City(val serverName: String) {
    BOBIGNY("BOBIGNY"),
    GENNEVILLIERS("GENNEVILLIERS"),
    MAISONS_ALFORT("MAISONS ALFORT"),
    RUNGIS("RUNGIS"),
    MASSY("MASSY"),
    NOISY_LE_GRAND("NOISY LE GRAND"),
    ROSNY_SOUS_BOIS("ROSNY SOUS BOIS"),
    SAINT_CLOUD("SAINT CLOUD"),
    SAINT_LEU_LA_FORET("SAINT LEU LA FORET"),
    VELIZY_VILLACOUBLAY("VELIZY VILLACOUBLAY")
}