package constants

enum class City(val serverName: String, val department: Department) {
    ROUEN_RIVE_DROITE("ROUEN RIVE DROITE",Department.D_76),
    ROUEN_RIVE_GAUCHE("ROUEN RIVE GAUCHE",Department.D_76),
    LE_HAVRE("LE HAVRE",Department.D_76),
    DIEPPE("DIEPPE",Department.D_76),
    SAINT_PRIEST("SAINT_PRIEST",Department.D_69),
    COLMAR("COLMAR",Department.D_68),
    MULHOUSE("MULHOUSE",Department.D_68),
    POUILLY("POUILLY",Department.D_57),
    SAINT_AVOLD("SAINT AVOLD",Department.D_57),
    SARREBOURG("SARREBOURG",Department.D_57),
    THIONVILLE("THIONVILLE",Department.D_57),
    FLEURY_LES_AUBRAIS("FLEURY LES AUBRAIS",Department.D_45),
    GIEN("GIEN",Department.D_45),
    OLIVET("OLIVET",Department.D_45),
    BOURGOIN_JALLIEU("BOURGOIN-JALLIEU",Department.D_38),
    LA_TRONCHE("LA TRONCHE",Department.D_38),
    MONTELIMAR_B("MONTELIMAR B",Department.D_26),
    VALENCE_B("VALENCE B",Department.D_26),
    AVON("AVON", Department.D_77),
    COULOMMIERS("COULOMMIERS", Department.D_77),
    LAGNY_SUR_MARNE("LAGNY SUR MARNE", Department.D_77),
    MEAUX("MEAUX", Department.D_77),
    MELUN("MELUN", Department.D_77),
    ACHERES("ACHERES", Department.D_78),
    MAGNANVILLE("MAGNANVILLE", Department.D_78),
    RAMBOUILLET("RAMBOUILLET", Department.D_78),
    SAINT_GERMAIN_EN_LAYE("SAINT GERMAIN EN LAYE", Department.D_78),
    TRAPPES("TRAPPES", Department.D_78),
    VELIZY_VILLACOUBLAY("VELIZY VILLACOUBLAY", Department.D_78),
    ETAMPES("ETAMPES", Department.D_91),
    EVRY("EVRY", Department.D_91),
    MASSY("MASSY", Department.D_91),
    MONTGERON("MONTGERON", Department.D_91),
    VILLABE("VILLABE", Department.D_91),
    ANTONY("ANTONY", Department.D_92),
    CLAMART("CLAMART", Department.D_92),
    GENNEVILLIERS("GENNEVILLIERS", Department.D_92),
    SAINT_CLOUD("SAINT CLOUD", Department.D_92),
    NANTERRE("NANTERRE", Department.D_92),
    BOBIGNY("BOBIGNY", Department.D_93),
    NOISY_LE_GRAND("NOISY LE GRAND", Department.D_93),
    ROSNY_SOUS_BOIS("ROSNY SOUS BOIS", Department.D_93),
    VILLEPINTE("VILLEPINTE", Department.D_93),
    RUNGIS("RUNGIS", Department.D_94),
    MAISONS_ALFORT("MAISONS ALFORT", Department.D_94),
    ARGENTEUIL("ARGENTEUIL", Department.D_95),
    CERGY("CERGY", Department.D_95),
    GONESSE("GONESSE", Department.D_95),
    PERSAN("PERSAN", Department.D_95),
    SAINT_BRICE("SAINT BRICE", Department.D_95),
    SAINT_LEU_LA_FORET("SAINT LEU LA FORET", Department.D_95),
}